CREATE TABLE IF NOT EXISTS item_vectors (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES items(id),
    vector TSVECTOR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 