DROP TABLE IF EXISTS item_vectors CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS phones CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
