version: '3.8'

services:
  # FastAPI сервис
  fastapi-app:
    build: ./resell-iphone-api
    ports:
      - "8015:8015"
    volumes:
      - ./resell-iphone-api:/app
      - ./shared_static:/app/static
    environment:
      - DB_NAME=postgres
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ALLOWED_ORIGINS=*
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ALLOWED_HEADERS=*
      - PAGINATION_LIMIT=10
    depends_on:
      - postgres-db

  # PostgreSQL сервис
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Telegram бот
  bot:
    build: ./resell-iphone-bot
    volumes:
      - ./resell-iphone-bot:/app
      - ./shared_static:/app/static
    environment:
      - API_HOST=http://fastapi-app:8015  # используем внутреннее имя сервиса
      # Добавьте другие переменные окружения для бота здесь
    depends_on:
      - fastapi-app

  # Prometheus сервис
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - fastapi-app
      - postgres-exporter

  # PostgreSQL Exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@postgres-db:5432/postgres?sslmode=disable
    depends_on:
      - postgres-db

  # Grafana сервис
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: