global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/recording_rules.yml"
  - "rules/alerting_rules.yml"

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi-app:8015']
    metrics_path: '/api/metrics'
    scheme: http
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scheme: http
    scrape_interval: 5s 