groups:
  - name: fastapi_alerts
    rules:
      # Алерт на высокую нагрузку
      - alert: HighRequestRate
        expr: sum(rate(fastapi_requests_total[5m])) by (method, path) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "Request rate is above 100 requests per second for 5 minutes"

      # Алерт на высокое время ответа
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, sum(rate(fastapi_request_duration_seconds_bucket[5m])) by (le, method, path)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile of response time is above 1 second for 5 minutes"

      # Алерт на ошибки
      - alert: HighErrorRate
        expr: sum(rate(fastapi_requests_total{status=~"5.."}[5m])) / sum(rate(fastapi_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for 5 minutes"

  - name: postgres_alerts
    rules:
      # Алерт на большое количество соединений
      - alert: HighConnectionCount
        expr: pg_stat_database_numbackends{datname="postgres"} > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of database connections"
          description: "Number of active connections is above 100 for 5 minutes"

      # Алерт на низкий кэш-хит
      - alert: LowCacheHitRatio
        expr: sum(pg_stat_database_blks_hit{datname="postgres"}) / (sum(pg_stat_database_blks_hit{datname="postgres"}) + sum(pg_stat_database_blks_read{datname="postgres"})) < 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit ratio"
          description: "Cache hit ratio is below 80% for 5 minutes"

      # Алерт на блокировки
      - alert: HighLockCount
        expr: pg_locks_count{datname="postgres"} > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of locks"
          description: "Number of locks is above 50 for 5 minutes" 